### ISSUE TITLE
Write the contract

### ISSUE THREAD

**Issue by schmidsi** [unchainedshop/lissajous-nft-experiment#3]
I started already here: https://github.com/xecutors/nft-project/blob/master/contracts/contracts/WhaleToken.sol

But I'd like to change a lot.

# TODOs
- [x] Remove access control and add ownable
- [ ] Constructor params: startBlock, endBlock, maxTokens (?), initialPrice, priceIncrease (10%), priceDecrease (1%), decreaseEpoch (6000)
- [ ] Store value and mintBlock during mint() on-chain
- [ ] Read functions to get color, frequencyX, ...

# Tests
- [ ] Mint before startblock: revert
- [ ] Mint after endBlock: revert
- [ ] Owner can withdraw ETH
- [ ] Only owner can withdraw ETH
- [ ] Price increases with every sale
- [ ] Price decreases over time
- [ ] It's not possible to mint 2 NFTs in the same block with the same value
