### ISSUE TITLE
Go-Live Checklist

### ISSUE THREAD

**Issue by schmidsi** [unchainedshop/lissajous-nft-experiment#7]
We can reuse it in other projects

- [x] Set the right parameters in deploy
- [ ] Ensure that console.log and other debugging tools are removed from contract source
- [x] Change network to mainnet
- [x] Verify contract on Etherscan
- [x] Link the contract on Etherscan
- [ ] Fill out Token Update Application Form on Etherscan
- [ ] Submit Token to OpenSea (better to have the test on rinkeby deployed there first)
